# Generated by Django 5.2.7 on 2025-10-11 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='babyparent',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='users.baby'),
        ),
        migrations.AddField(
            model_name='babyparent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='classification_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='父类名'),
        ),
        migrations.AddField(
            model_name='articles',
            name='categorys',
            field=models.ManyToManyField(to='main.category', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='checkuprecord',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup_records', to='users.baby'),
        ),
        migrations.AddField(
            model_name='checkuprecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.baby'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measurement',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='users.baby'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='measured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationrecord',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_records', to='users.baby'),
        ),
        migrations.AddField(
            model_name='medicationrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='main.milestonetype'),
        ),
        migrations.AddField(
            model_name='photo',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.baby'),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='events', to='main.photo'),
        ),
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='users.baby'),
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(to='main.tag', verbose_name='所有标签'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccine',
            unique_together={('name', 'dose')},
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_records', to='users.baby'),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vaccine'),
        ),
        migrations.AlterUniqueTogether(
            name='babyparent',
            unique_together={('baby', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('baby', 'measure_date')},
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['baby', 'record_date'], name='main_record_baby_id_259df5_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['category', 'record_date'], name='main_record_categor_94acf0_idx'),
        ),
    ]
