# Generated by Django 5.2.7 on 2025-10-14 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='articlecomments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.articles', verbose_name='关联文章'),
        ),
        migrations.AddField(
            model_name='babyparent',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='users.baby'),
        ),
        migrations.AddField(
            model_name='babyparent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='classification_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='父类名'),
        ),
        migrations.AddField(
            model_name='articles',
            name='categorys',
            field=models.ManyToManyField(to='main.category', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='checkuprecord',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup_records', to='users.baby'),
        ),
        migrations.AddField(
            model_name='checkuprecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collect',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articles', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='event',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.baby'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articles', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='users.baby'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='measured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationrecord',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_records', to='users.baby'),
        ),
        migrations.AddField(
            model_name='medicationrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='main.milestonetype'),
        ),
        migrations.AddField(
            model_name='photo',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.baby'),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='events', to='main.photo'),
        ),
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='users.baby'),
        ),
        migrations.AddField(
            model_name='photo',
            name='record',
            field=models.ForeignKey(help_text='该照片属于哪条成长记录', on_delete=django.db.models.deletion.CASCADE, related_name='related_photos', to='main.record', verbose_name='所属记录'),
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(to='main.tag', verbose_name='所有标签'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccine',
            unique_together={('name', 'dose')},
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_records', to='users.baby'),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vaccine'),
        ),
        migrations.AddIndex(
            model_name='articlecomments',
            index=models.Index(fields=['article', '-create_time'], name='main_articl_article_df450f_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecomments',
            index=models.Index(fields=['user', '-create_time'], name='main_articl_user_id_0c34c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='babyparent',
            unique_together={('baby', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='collect',
            unique_together={('user', 'article')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'article')},
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('baby', 'measure_date')},
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['baby', '-record_date', 'category'], name='main_record_baby_id_48c8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['author', '-created_at'], name='main_record_author__422123_idx'),
        ),
    ]
