# Generated by Django 5.2.7 on 2025-10-15 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='record',
            field=models.ForeignKey(blank=True, help_text='该照片属于哪条成长记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_photos', to='main.record', verbose_name='所属记录'),
        ),
    ]
