# Generated by Django 5.2.7 on 2025-10-13 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_collect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='评论时间')),
                ('like_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='点赞数')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.articles', verbose_name='关联文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['article', '-create_time'], name='main_articl_article_df450f_idx'), models.Index(fields=['user', '-create_time'], name='main_articl_user_id_0c34c8_idx')],
            },
        ),
    ]
