# Generated by Django 5.2.7 on 2025-10-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_photo_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.articlecomments', verbose_name='父评论'),
        ),
    ]
